import { View, Text, TextInput, Button, TouchableOpacity, Alert, ActivityIndicator } from 'react-native'
import React from 'react'
import { router } from 'expo-router'
import { aiModel } from '~/src/ai/ai'
import prompt from '~/src/ai/prompt'
import { useState } from 'react'
import {jsonrepair} from 'jsonrepair'




const CreateCourse = () => {
 const [loading, setLoading] = useState(false)
 const [topic, setTopic] = useState([])
//  want to store in array of topic selected
 const [selectedTopics, setSelectedTopics] = useState([])
 console.log("TOPIC :",topic);
 console.log("TOPIC TYPEOf  :",typeof topic);

 
const onTopicSelect = (topic) => {
  const isAlreadyExist = selectedTopics.find((item)=> item === topic)
  if(!isAlreadyExist){
    setSelectedTopics((prev)=>( [...prev, topic]))
  }else{
  const topics = selectedTopics.filter((item) => (item!==topic));
  setSelectedTopics(topics)
}
}

const isTopicSelected = () => {
  const selection = selectedTopics.find((item)=>(item === topic))
  return selection?true:false
}
  // Generating topics 
  const onGenerateTopic = async() => {
      try {
        setLoading(true)
        const response = await aiModel("Python" + prompt.IDEA)
        console.log("Response Topic generated by AI :",response);
        // this reparedJSOn if for repairing json 
        const repairedJson = await jsonrepair(response)
        console.log("repairedJson :", typeof repairedJson);
        // Don't foreget to convert in json object
        setTopic(JSON.parse(repairedJson))
      } catch (error) {
        console.log("Error from generatTopic funtion error", error);
        Alert.alert("Error",'Failed to Generate Topics')
      }finally{
        setLoading(false)
      }
      // console.log("hello");
  }
  return (
    <View>
      <Text>CreateCourse</Text>
      <TextInput 
      placeholder={"Write your text"}
      // value= 'Write your text'

      // This textinput is for online one line
      // numberOfLines={3} 
          multiline={true}
                      numberOfLines={4}
     // SOMETIMES ClassName height width props 
     // have some problem in TextInput so
     // it takes time to execute 
     // so for this use Style 
      // style={{height: 100, }}

      // when you add height then cursor will start from middle 
      // so use align-top to alig ing it top 
      className=" mb-6 h-28    align-top border rounded-2xl bg-white  text-black"

      />
      {/* Add activity indicator */}

{/* While generating disable the button */}
<TouchableOpacity
            onPress={onGenerateTopic}
 disabled={loading}
className='  bg-green-500  p-2  justify-center items-center'
>
  {
    loading?(<ActivityIndicator size={"small"} color={"blue"}/>):(
    <Text className='rounded-xl font-roboto- text-white text-2xl'>Create Topic </Text>)
  }
</TouchableOpacity>

{/* what ? I want that this JSX code should show on screen 
How? Basically in React code execute line by line when it reaches to this 
// code then will see is this function returning anything ?yeah then 
// it will show this code 

*/}
{/* In life you will 
get a lot of times this kinda error then remind yourself 
that map metod works only for array and your json must be strinigify json so
 convert in JSON object by parsing it
 TypeError: topic?.map is not a function
(because .map() doesn’t work on strings
 */}



{/* Container for all the topics */}
 <View className='mb-6'>
{

  
 topic?.map((item, index) => {
  // console.log("ITems :",item);
  // This map method runs a loop over 
  // array then returns it's indexes in a key called index 
  // then you have to provide key to conatiner so that it map 
  // method know that this to render basically for performance    
  // console.log("Index :",index);
  
    return(
      // You need this view
      //  cause key can be use only in vew props
      // otherwise it has no use 
      // btw it's container for each time 
      // which is also that touchable so no use 
      <View   key={index}>

        {/* I didn't know that if yu write here w-40 then 
        it will only take space till 40 */}
        <TouchableOpacity 
       onPress={() => onTopicSelect(topic)}
       className={` border mb-3 p-1.5 rounded-2xl ${isTopicSelected()? 'bg-blue-600': 'bg-red-600'} `}>
         <Text className='font-roboto-semibold text-black'
         numberOfLines={1}
         >Topic {item}</Text>
         {/* <Text className='  '>Python Data Structures: List and Dictionsares fdsfds</Text> */}
         </TouchableOpacity>
         </View>
    )
  })
}
 </View>


{/* <TouchableOpacity
            // onPress={onGenerateTopic}
 disabled={loading}
className=' mt-6 bg-green-500  p-2  justify-center items-center'
>
  {
    loading?(<ActivityIndicator size={"small"} color={"blue"}/>):(
    <Text className='   rounded-xl font-roboto- text-white text-2xl'>Generate Course</Text>)
  }
</TouchableOpacity> */}



{/* 
         <Button 
            title= 'Create a course'
            onPress={onGenerateTopic}
            />
 */}
            {/* For selecting topics */}
            
      
    </View>
  )
}

export default CreateCourse