import dedent from "dedent";

// so we have here we have
//  two keys IDEA and COURSE
// Look if you want ot write multi line string 
// then you can't write using quotes why? cause 
// quotes doesn't support new line why?
// instead use backtic cause it support it 
// then why dedent ?
// cause it removes white spaces  

// let's learn about white spaces 
// there a lot of types will talk about two 
// 1. Normal: ( ) white space is created between round bracket
// 2. New line: whenever you enter a new line a 
// white space is created called n\(new line character) 
// which is white space 

// so we want to remove white spaces in 
// our prompt so that LLM can't confuse that's why using 
// dedent  
// btw dedent syntax:  dedent`write your text`
//   As your are coaching teacher 
    // - User want to learn about the topic
    // - Generate 5-7 Course title for study (Short)
    // - Make sure it is releated to description
    // - Output will be ARRAY of String in JSON FORMAT only
    // - Do not add any plain text in output,
    // PROMPT SHOULD BE LIKE THIS BELOW NOTHING JUST DATA THAT'S IT. 
    // lodu tujhe samjh nahi aata kya ? 
    // I don't need this: "Here is the response in the exact format you requested:"
    // I only once need this data 
export default {
  IDEA: dedent`: As a course expert:
- User wants to learn the topic.
- Generate 5-7 short, beginner-friendly course titles.
- Make sure they are related to the description.
- Respond with an ARRAY of STRINGS in valid JSON format.
- DO NOT include any other text, no explanations, no labels like "Input" or "Output".
- Just return the array, nothing else.
    [
    "Introduction to Python Programming",
    "Data Structures and Algorithms in Python",
    "Python for Data Science and Machine Learning",
    "Web Development with Python and Django",
    "Automation and Scripting with Python",
    "Object-Oriented Programming in Python",
    "Python for Cybersecurity and Ethical Hacking"
]
    `,
  // - Chapter Explain in HTML Form, (Code example if required), add line break if required
COURSE:`
As you are a coaching teacher:
- The user wants to learn about all topics.
- Create 2 courses with Course Name, Description, and 2 Chapters in each course.
- Make sure to include chapters.
- List content in each chapter along with a description (1 to 2 lines each).
- Do not just explain what the chapter is about—explain in detail with examples.
- Include Easy, Moderate, and Advanced courses depending on the topics.
- Randomly select a CourseBanner image from ('/banner1.png','/banner2.png','/banner3.png','/banner4.png','/banner5.png','/banner6.png').
- Explain chapter content as a detailed tutorial with a list of topics.
- Generate 2 quizzes, 2 flashcards, and 2 question-answer pairs.
- Tag each course with one of the following categories: ["Tech & Coding", "Business & Finance", "Health & Fitness", "Science & Engineering", "Arts & Creativity"].
- Output only in JSON format—do not return only data that's it don't return anyhting else just data in JSON format 
don't return anything like: ### Key Features or this 
Sure! Here's a structured JSON response with two courses, each containing detailed chapters, quizzes, 
flashcards, and Q&A pairs, along with a randomly selected ban
Just return data in JSON fomrat that's it 
ek baat sun le lodu I dont' need this: Response Topic generated by AI : "Sure! Here is the structured JSON data as requested:"
this kinda things 
create only one course
[
  {
    "course_name": "Introduction to Python Programming",
    "description": "A beginner-friendly course to learn Python from scratch. Covers basics like variables, loops, and functions, and progresses to more advanced topics like object-oriented programming.",
    "category": "Tech & Coding",
    "banner_image": "/banner3.png",
    "chapters": [
      {
        "chapter_title": "Python Basics",
        "content": [
          {
            "topic": "Variables and Data Types",
            "description": "Learn how to declare variables and understand different data types in Python. Example: \`name = 'Alice'\` (string), \`age = 25\` (integer)."
          },
          {
            "topic": "Conditional Statements",
            "description": "Use \`if-elif-else\` to control program flow. Example: Checking if a number is positive, negative, or zero."
          }
        ]
      },
      {
        "chapter_title": "Functions and Loops",
        "content": [
          {
            "topic": "Defining Functions",
            "description": "Create reusable code blocks with \`def\`. Example: A function to add two numbers."
          },
          {
            "topic": "For and While Loops",
            "description": "Iterate over sequences with \`for\` and \`while\`. Example: Printing numbers from 1 to 10."
          }
        ]
      }
    ],
    "quizzes": [
      {
        "question": "What is the output of \`print(3 + 2 * 2)\`?",
        "options": ["7", "10", "5", "Error"],
        "answer": "7"
      },
      {
        "question": "Which keyword is used to define a function in Python?",
        "options": ["func", "define", "def", "function"],
        "answer": "def"
      }
    ],
    "flashcards": [
      {
        "front": "What is Python?",
        "back": "A high-level, interpreted programming language known for readability."
      },
      {
        "front": "What does \`len()\` do?",
        "back": "Returns the length of a string, list, or other iterable."
      }
    ],
    "qa_pairs": [
      {
        "question": "How do you comment in Python?",
        "answer": "Use \`#\` for single-line comments and \`\`\` or \\"\\"\\" for multi-line comments."
      },
      {
        "question": "What is a list in Python?",
        "answer": "An ordered, mutable collection of items enclosed in \`[]\`."
      }
    ]
  },
 
    ]
  }
]
`
}